name: 'Docker Build & Push for Medusa'
description: 'Docker Build & Push for Medusa'

inputs:
  GITHUB_TOKEN:
    description: 'github token needed for docker credentials'
    required: true

  DOCKER_REPOSITORY:
    description: 'docker image repository'
    required: true

  DOCKER_TAG:
    description: 'docker image tag'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        memory: "4096M"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github actions
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ inputs.GITHUB_TOKEN }}'

    - name: Build and Push AMD64
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: apps/medusa/Dockerfile
        platforms: linux/amd64
        tags: ${{ inputs.DOCKER_REPOSITORY }}:${{ github.sha }}-amd64
    
    - name: Build and Push ARM64
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: apps/medusa/Dockerfile
        platforms: linux/arm64
        tags: ${{ inputs.DOCKER_REPOSITORY }}:${{ github.sha }}-arm64
