name: Medusa Docker Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # This allows pushing to GHCR

jobs:
  build-and-push-medusa:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        uses: ./.github/composite/monorepo-install

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build Packages
        run: yarn build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Medusa Docker (AMD64)
        uses: ./.github/composite/docker/medusa
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REPOSITORY: ghcr.io/${{ github.repository_owner }}/medusa-docker
          DOCKER_TAG: ${{ github.sha }}-amd64
          PLATFORM: linux/amd64

      - name: Push Medusa Docker (ARM64)
        uses: ./.github/composite/docker/medusa
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REPOSITORY: ghcr.io/${{ github.repository_owner }}/medusa-docker
          DOCKER_TAG: ${{ github.sha }}-arm64
          PLATFORM: linux/arm64
          
      - name: Create and Push Multi-Arch Manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/medusa-docker:latest \
            --amend ghcr.io/${{ github.repository_owner }}/medusa-docker:${{ github.sha }}-amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/medusa-docker:${{ github.sha }}-arm64

          docker manifest push ghcr.io/${{ github.repository_owner }}/medusa-docker:latest