name: Medusa Docker Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # This allows pushing to GHCR

jobs:
  build-and-push-medusa:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        uses: ./.github/composite/monorepo-install

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build Packages
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Medusa Docker (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/medusa-docker:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/medusa-docker:latest
